// 完整词汇题库 - 人教版PEP教材三年级至六年级
window.vocabularyDatabase = {
    grade3: {
        // 三年级上册
        semester1: [
            { word: "pen", chinese: "钢笔" },
            { word: "pencil", chinese: "铅笔" },
            { word: "book", chinese: "书" },
            { word: "ruler", chinese: "尺子" },
            { word: "bag", chinese: "包" },
            { word: "red", chinese: "红色" },
            { word: "blue", chinese: "蓝色" },
            { word: "yellow", chinese: "黄色" },
            { word: "green", chinese: "绿色" },
            { word: "white", chinese: "白色" },
            { word: "black", chinese: "黑色" },
            { word: "orange", chinese: "橙色" },
            { word: "brown", chinese: "棕色" },
            { word: "face", chinese: "脸" },
            { word: "ear", chinese: "耳朵" },
            { word: "eye", chinese: "眼睛" },
            { word: "nose", chinese: "鼻子" },
            { word: "mouth", chinese: "嘴巴" },
            { word: "hand", chinese: "手" },
            { word: "arm", chinese: "手臂" },
            { word: "head", chinese: "头" },
            { word: "body", chinese: "身体" },
            { word: "leg", chinese: "腿" },
            { word: "foot", chinese: "脚" },
            { word: "one", chinese: "一" },
            { word: "two", chinese: "二" },
            { word: "three", chinese: "三" },
            { word: "four", chinese: "四" },
            { word: "five", chinese: "五" },
            { word: "six", chinese: "六" },
            { word: "seven", chinese: "七" },
            { word: "eight", chinese: "八" },
            { word: "nine", chinese: "九" },
            { word: "ten", chinese: "十" },
            { word: "cat", chinese: "猫" },
            { word: "dog", chinese: "狗" },
            { word: "bird", chinese: "鸟" },
            { word: "pig", chinese: "猪" },
            { word: "duck", chinese: "鸭子" }
        ],
        // 三年级下册
        semester2: [
            { word: "father", chinese: "父亲" },
            { word: "mother", chinese: "母亲" },
            { word: "brother", chinese: "兄弟" },
            { word: "sister", chinese: "姐妹" },
            { word: "grandfather", chinese: "祖父" },
            { word: "grandmother", chinese: "祖母" },
            { word: "teacher", chinese: "老师" },
            { word: "student", chinese: "学生" },
            { word: "friend", chinese: "朋友" },
            { word: "apple", chinese: "苹果" },
            { word: "banana", chinese: "香蕉" },
            { word: "pear", chinese: "梨" },
            { word: "orange", chinese: "橙子" },
            { word: "strawberry", chinese: "草莓" },
            { word: "watermelon", chinese: "西瓜" },
            { word: "eleven", chinese: "十一" },
            { word: "twelve", chinese: "十二" },
            { word: "thirteen", chinese: "十三" },
            { word: "fourteen", chinese: "十四" },
            { word: "fifteen", chinese: "十五" },
            { word: "sixteen", chinese: "十六" },
            { word: "seventeen", chinese: "十七" },
            { word: "eighteen", chinese: "十八" },
            { word: "nineteen", chinese: "十九" },
            { word: "twenty", chinese: "二十" },
            { word: "kite", chinese: "风筝" },
            { word: "ball", chinese: "球" },
            { word: "car", chinese: "汽车" },
            { word: "boat", chinese: "小船" },
            { word: "map", chinese: "地图" },
            { word: "cap", chinese: "帽子" },
            { word: "desk", chinese: "书桌" },
            { word: "chair", chinese: "椅子" },
            { word: "box", chinese: "盒子" },
            { word: "toy", chinese: "玩具" },
            { word: "doll", chinese: "洋娃娃" }
        ]
    },
    grade4: {
        // 四年级上册
        semester1: [
            { word: "classroom", chinese: "教室" },
            { word: "window", chinese: "窗户" },
            { word: "door", chinese: "门" },
            { word: "floor", chinese: "地板" },
            { word: "blackboard", chinese: "黑板" },
            { word: "light", chinese: "灯" },
            { word: "picture", chinese: "图画" },
            { word: "computer", chinese: "电脑" },
            { word: "fan", chinese: "风扇" },
            { word: "wall", chinese: "墙" },
            { word: "schoolbag", chinese: "书包" },
            { word: "math", chinese: "数学" },
            { word: "Chinese", chinese: "语文" },
            { word: "English", chinese: "英语" },
            { word: "music", chinese: "音乐" },
            { word: "art", chinese: "美术" },
            { word: "PE", chinese: "体育" },
            { word: "candy", chinese: "糖果" },
            { word: "cake", chinese: "蛋糕" },
            { word: "bread", chinese: "面包" },
            { word: "rice", chinese: "米饭" },
            { word: "noodle", chinese: "面条" },
            { word: "soup", chinese: "汤" },
            { word: "milk", chinese: "牛奶" },
            { word: "juice", chinese: "果汁" },
            { word: "water", chinese: "水" },
            { word: "beef", chinese: "牛肉" },
            { word: "chicken", chinese: "鸡肉" },
            { word: "fish", chinese: "鱼" },
            { word: "vegetable", chinese: "蔬菜" },
            { word: "bedroom", chinese: "卧室" },
            { word: "kitchen", chinese: "厨房" },
            { word: "bathroom", chinese: "浴室" },
            { word: "living room", chinese: "客厅" },
            { word: "study", chinese: "书房" },
            { word: "sofa", chinese: "沙发" },
            { word: "fridge", chinese: "冰箱" },
            { word: "phone", chinese: "电话" }
        ],
        // 四年级下册
        semester2: [
            { word: "library", chinese: "图书馆" },
            { word: "playground", chinese: "操场" },
            { word: "garden", chinese: "花园" },
            { word: "computer room", chinese: "电脑室" },
            { word: "art room", chinese: "美术室" },
            { word: "music room", chinese: "音乐室" },
            { word: "lunch", chinese: "午餐" },
            { word: "breakfast", chinese: "早餐" },
            { word: "dinner", chinese: "晚餐" },
            { word: "get up", chinese: "起床" },
            { word: "go to school", chinese: "去上学" },
            { word: "go home", chinese: "回家" },
            { word: "go to bed", chinese: "睡觉" },
            { word: "weather", chinese: "天气" },
            { word: "sunny", chinese: "晴朗的" },
            { word: "rainy", chinese: "下雨的" },
            { word: "cloudy", chinese: "多云的" },
            { word: "windy", chinese: "有风的" },
            { word: "snowy", chinese: "下雪的" },
            { word: "cold", chinese: "寒冷的" },
            { word: "warm", chinese: "温暖的" },
            { word: "cool", chinese: "凉爽的" },
            { word: "hot", chinese: "炎热的" },
            { word: "sheep", chinese: "绵羊" },
            { word: "hen", chinese: "母鸡" },
            { word: "horse", chinese: "马" },
            { word: "cow", chinese: "奶牛" },
            { word: "lamb", chinese: "小羊" },
            { word: "goat", chinese: "山羊" },
            { word: "tomato", chinese: "西红柿" },
            { word: "potato", chinese: "土豆" },
            { word: "carrot", chinese: "胡萝卜" },
            { word: "green bean", chinese: "豆角" },
            { word: "cucumber", chinese: "黄瓜" },
            { word: "onion", chinese: "洋葱" }
        ]
    },
    grade5: {
        // 五年级上册
        semester1: [
            { word: "clever", chinese: "聪明的" },
            { word: "polite", chinese: "有礼貌的" },
            { word: "hard-working", chinese: "勤奋的" },
            { word: "helpful", chinese: "乐于助人的" },
            { word: "strict", chinese: "严格的" },
            { word: "shy", chinese: "害羞的" },
            { word: "Monday", chinese: "星期一" },
            { word: "Tuesday", chinese: "星期二" },
            { word: "Wednesday", chinese: "星期三" },
            { word: "Thursday", chinese: "星期四" },
            { word: "Friday", chinese: "星期五" },
            { word: "Saturday", chinese: "星期六" },
            { word: "Sunday", chinese: "星期日" },
            { word: "weekend", chinese: "周末" },
            { word: "sandwich", chinese: "三明治" },
            { word: "salad", chinese: "沙拉" },
            { word: "hamburger", chinese: "汉堡包" },
            { word: "ice cream", chinese: "冰淇淋" },
            { word: "tea", chinese: "茶" },
            { word: "fresh", chinese: "新鲜的" },
            { word: "healthy", chinese: "健康的" },
            { word: "delicious", chinese: "美味的" },
            { word: "hot", chinese: "辣的" },
            { word: "sweet", chinese: "甜的" },
            { word: "sing", chinese: "唱歌" },
            { word: "dance", chinese: "跳舞" },
            { word: "draw", chinese: "画画" },
            { word: "cartoon", chinese: "卡通" },
            { word: "cook", chinese: "做饭" },
            { word: "swim", chinese: "游泳" },
            { word: "play basketball", chinese: "打篮球" },
            { word: "play football", chinese: "踢足球" },
            { word: "ping-pong", chinese: "乒乓球" },
            { word: "speak English", chinese: "说英语" },
            { word: "clock", chinese: "时钟" },
            { word: "plant", chinese: "植物" },
            { word: "photo", chinese: "照片" },
            { word: "bike", chinese: "自行车" },
            { word: "season", chinese: "季节" },
            { word: "spring", chinese: "春天" },
            { word: "summer", chinese: "夏天" },
            { word: "autumn", chinese: "秋天" },
            { word: "winter", chinese: "冬天" },
            { word: "picnic", chinese: "野餐" },
            { word: "go on a picnic", chinese: "去野餐" },
            { word: "pick", chinese: "采摘" },
            { word: "snowman", chinese: "雪人" }
        ],
        // 五年级下册
        semester2: [
            { word: "eat breakfast", chinese: "吃早餐" },
            { word: "do morning exercises", chinese: "做早操" },
            { word: "play sports", chinese: "做运动" },
            { word: "eat dinner", chinese: "吃晚餐" },
            { word: "clean my room", chinese: "打扫我的房间" },
            { word: "go for a walk", chinese: "散步" },
            { word: "go shopping", chinese: "购物" },
            { word: "take a dancing class", chinese: "上舞蹈课" },
            { word: "January", chinese: "一月" },
            { word: "February", chinese: "二月" },
            { word: "March", chinese: "三月" },
            { word: "April", chinese: "四月" },
            { word: "May", chinese: "五月" },
            { word: "June", chinese: "六月" },
            { word: "July", chinese: "七月" },
            { word: "August", chinese: "八月" },
            { word: "September", chinese: "九月" },
            { word: "October", chinese: "十月" },
            { word: "November", chinese: "十一月" },
            { word: "December", chinese: "十二月" },
            { word: "first", chinese: "第一" },
            { word: "second", chinese: "第二" },
            { word: "third", chinese: "第三" },
            { word: "fourth", chinese: "第四" },
            { word: "fifth", chinese: "第五" },
            { word: "twelfth", chinese: "第十二" },
            { word: "twentieth", chinese: "第二十" },
            { word: "climb", chinese: "攀爬" },
            { word: "drink", chinese: "喝" },
            { word: "sleep", chinese: "睡觉" },
            { word: "jump", chinese: "跳跃" },
            { word: "walk", chinese: "走" },
            { word: "run", chinese: "跑" },
            { word: "fly", chinese: "飞" },
            { word: "mine", chinese: "我的" },
            { word: "yours", chinese: "你的" },
            { word: "his", chinese: "他的" },
            { word: "hers", chinese: "她的" },
            { word: "theirs", chinese: "他们的" },
            { word: "ours", chinese: "我们的" }
        ]
    },
    grade6: {
        // 六年级上册
        semester1: [
            { word: "science", chinese: "科学" },
            { word: "museum", chinese: "博物馆" },
            { word: "post office", chinese: "邮局" },
            { word: "bookstore", chinese: "书店" },
            { word: "cinema", chinese: "电影院" },
            { word: "hospital", chinese: "医院" },
            { word: "crossing", chinese: "十字路口" },
            { word: "turn left", chinese: "左转" },
            { word: "turn right", chinese: "右转" },
            { word: "go straight", chinese: "直走" },
            { word: "bus", chinese: "公共汽车" },
            { word: "plane", chinese: "飞机" },
            { word: "taxi", chinese: "出租车" },
            { word: "ship", chinese: "船" },
            { word: "subway", chinese: "地铁" },
            { word: "train", chinese: "火车" },
            { word: "traffic", chinese: "交通" },
            { word: "traffic light", chinese: "交通灯" },
            { word: "dictionary", chinese: "字典" },
            { word: "comic", chinese: "漫画" },
            { word: "word book", chinese: "单词书" },
            { word: "postcard", chinese: "明信片" },
            { word: "visit", chinese: "拜访" },
            { word: "film", chinese: "电影" },
            { word: "trip", chinese: "旅行" },
            { word: "supermarket", chinese: "超市" },
            { word: "evening", chinese: "晚上" },
            { word: "tonight", chinese: "今晚" },
            { word: "tomorrow", chinese: "明天" },
            { word: "next week", chinese: "下周" },
            { word: "hobby", chinese: "爱好" },
            { word: "puzzle", chinese: "拼图" },
            { word: "hiking", chinese: "远足" },
            { word: "pen pal", chinese: "笔友" },
            { word: "hobby", chinese: "爱好" },
            { word: "jasmine", chinese: "茉莉" },
            { word: "amazing", chinese: "令人惊讶的" },
            { word: "shall", chinese: "应该" },
            { word: "police officer", chinese: "警察" },
            { word: "postman", chinese: "邮递员" },
            { word: "businessman", chinese: "商人" },
            { word: "fisherman", chinese: "渔民" },
            { word: "scientist", chinese: "科学家" },
            { word: "pilot", chinese: "飞行员" },
            { word: "coach", chinese: "教练" },
            { word: "factory", chinese: "工厂" },
            { word: "worker", chinese: "工人" },
            { word: "angry", chinese: "生气的" },
            { word: "afraid", chinese: "害怕的" },
            { word: "sad", chinese: "伤心的" },
            { word: "worried", chinese: "担心的" },
            { word: "happy", chinese: "高兴的" }
        ],
        // 六年级下册
        semester2: [
            { word: "younger", chinese: "更年轻的" },
            { word: "older", chinese: "更年长的" },
            { word: "taller", chinese: "更高的" },
            { word: "shorter", chinese: "更矮的" },
            { word: "longer", chinese: "更长的" },
            { word: "thinner", chinese: "更瘦的" },
            { word: "heavier", chinese: "更重的" },
            { word: "bigger", chinese: "更大的" },
            { word: "smaller", chinese: "更小的" },
            { word: "stronger", chinese: "更强壮的" },
            { word: "dinosaur", chinese: "恐龙" },
            { word: "hall", chinese: "大厅" },
            { word: "magazine", chinese: "杂志" },
            { word: "hotel", chinese: "旅馆" },
            { word: "bad", chinese: "坏的" },
            { word: "broken", chinese: "破损的" },
            { word: "stayed", chinese: "停留" },
            { word: "watched", chinese: "观看" },
            { word: "cleaned", chinese: "打扫" },
            { word: "washed", chinese: "洗" },
            { word: "drank", chinese: "喝" },
            { word: "saw", chinese: "看见" },
            { word: "read", chinese: "阅读" },
            { word: "slept", chinese: "睡觉" },
            { word: "had", chinese: "有" },
            { word: "cold", chinese: "感冒" },
            { word: "had a cold", chinese: "感冒" },
            { word: "yesterday", chinese: "昨天" },
            { word: "ago", chinese: "以前" },
            { word: "last weekend", chinese: "上周末" },
            { word: "gym", chinese: "体育馆" },
            { word: "active", chinese: "活跃的" },
            { word: "quiet", chinese: "安静的" },
            { word: "heavy", chinese: "重的" },
            { word: "light", chinese: "轻的" },
            { word: "go cycling", chinese: "骑自行车" },
            { word: "ice-skate", chinese: "滑冰" },
            { word: "badminton", chinese: "羽毛球" },
            { word: "dream", chinese: "梦" },
            { word: "sleepy", chinese: "困倦的" },
            { word: "study", chinese: "学习" },
            { word: "university", chinese: "大学" },
            { word: "goal", chinese: "目标" },
            { word: "become", chinese: "成为" }
        ]
    }
};
